Listado de alertas SQL

GRAVEDAD 17 iNDICA RECURSOS INSUFICIENTES EJ FALTA DE ESPACIO
GRAVEDAD 19 iNDICA QUE HA SUPERADO LOS RECURSOS INTERNOS
GRAVEDAD 20 iNDICA ERROR FATAL DE CONEXION
GRAVEDAD 21 iNDICA ERROR FATAL DE CONEXION QUE AFECTA A LAS BASES Y LAS TABLAs
GRAVEDAD 22 iNDICA ERROR EN LA TABLA O INDICE QUE FUE DAÑADO
GRAVEDAD 23 iNDICA ERROR EN LA BASE DE DATOS DEBIDO A PROBLEMAS DE HARDWARE
GRAVEDAD 24 iNDICA ERROR A NIVEL HARDWARE
GRAVEDAD 25 iNDICA QUE HA OCURRIDO UN ERROR INTERNO DEL SISTEMA
