USE [master]
ALTER DATABASE [VFHome] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [VFHome] FROM  DISK = N'K:\SSVFN-01\VFHome\FULL\SSVFN-01_VFHome.bak' 
WITH  FILE = 1,  
MOVE N'vfHomeAlfa' TO N'I:\MSSQL2K14\MSSQL12.MSSQLSERVER\MSSQL\Data\VFHome.mdf',  
MOVE N'vfHomeAlfa_log' TO N'H:\MSSQL2K14\MSSQL12.MSSQLSERVER\MSSQL\Data\VFHome_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [VFHome] SET MULTI_USER
GO

USE [master]
ALTER DATABASE [VFNET] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [VFNET] FROM  DISK = N'K:\SSVFN-01\VFNET\FULL\SSVFN-01_VFNET.bak' 
WITH  FILE = 1,  
MOVE N'vfNet_1_0_0' TO N'I:\MSSQL2K14\MSSQL12.MSSQLSERVER\MSSQL\Data\VFNET.mdf',  
MOVE N'vfNet_1_0_0_log' TO N'H:\MSSQL2K14\MSSQL12.MSSQLSERVER\MSSQL\Data\VFNET_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [VFNET] SET MULTI_USER
GO

USE [master]
ALTER DATABASE [VFondos] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [VFondos] FROM  DISK = N'K:\SSVFN-01\VFondos\FULL\SSVFN-01_VFondos.bak' 
WITH  FILE = 1,  
MOVE N'VFSupervielleDef_Data' TO N'I:\MSSQL2K14\MSSQL12.MSSQLSERVER\MSSQL\Data\vfondos.mdf',  
MOVE N'VFSupervielleDef_Log' TO N'H:\MSSQL2K14\MSSQL12.MSSQLSERVER\MSSQL\Data\vfondos_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [VFondos] SET MULTI_USER
GO

USE [master]
ALTER DATABASE [B04_APLICACIONES] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [B04_APLICACIONES] FROM  DISK = N'K:\SSVFN-01\B04_APLICACIONES\FULL\SSVFN-01_B04_APLICACIONES.bak' 
WITH  FILE = 1,  
MOVE N'B04_APLICACIONES' TO N'I:\MSSQL2K14\MSSQL12.MSSQLSERVER\MSSQL\Data\B04_APLICACIONES.mdf',  
MOVE N'B04_APLICACIONES_log' TO N'H:\MSSQL2K14\MSSQL12.MSSQLSERVER\MSSQL\Data\B04_APLICACIONES_1.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [B04_APLICACIONES] SET MULTI_USER
GO